### ISSUE TITLE
Speed up the scraper

### ISSUE THREAD

**Issue by vamsitadikonda** [vamsitadikonda/slash#1]
The web scraper is too slow. Speed up the process by adding multithreading.

**Comment by Swimitha** [comment]
Hey Guys, I was able to double the speed by twice using multithreading. We need to improve it further

**Comment by vamsitadikonda** [comment]
Why not use multiprocessing ?

**Comment by vamsitadikonda** [comment]
I found this parser to be really fast. Link : https://github.com/rushter/selectolax

**Comment by Swimitha** [comment]
Can you try implementing it and see

**Comment by vamsitadikonda** [comment]
I have implemented the new HTML parser
